apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: secure-app
  labels:
    app: secure-app
    component: backend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: secure-app
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secure-app
  labels:
    app: secure-app
    component: frontend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: secure-app
    component: frontend









