apiVersion: v1
kind: Secret
metadata:
  name: gitlab-admin-credentials
  namespace: gitlab-system
type: Opaque
stringData:
  # GitLab first user is always "root"; password set to openshift for easy access
  username: root
  password: openshift

