apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quay

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - wait-for-operator.yaml
  - quay-config-bundle.yaml
  - quayregistry.yaml
  - quay-registry-setup-job.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: rhtas-demo
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
