apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhpds-gitea-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/rhpds/gitea-catalog:latest
  displayName: RHPDS Gitea Operator
