apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - central.yaml
  - secured-cluster.yaml
  - api-token-secret.yaml
  - acs-admin-password-secret.yaml
  - init-api-token-job.yaml
  - acs-reset-admin-password-job.yaml
  - acs-jenkins-credentials-rbac.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: rhtas-demo
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
