apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.13.3
    releaseName: sealed-secrets
    namespace: kube-system
    valuesInline:
      fullnameOverride: sealed-secrets-controller
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 256Mi

namespace: kube-system
