# Accept signatures from Jenkins develop or main branch pipelines
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-develop-or-main-signature
  labels:
    app.kubernetes.io/part-of: rhtas-demo
    policy-category: identity
  annotations:
    description: "Accept signatures from Jenkins develop or main branch"
spec:
  images:
    - glob: "registry-quay-quay.__CLUSTER_DOMAIN__/secure-app/**"
  authorities:
    - keyless:
        identities:
          - issuer: https://jenkins.__CLUSTER_DOMAIN__/oidc
            subjectRegExp: ".*/job/secure-app/job/(develop|main)/?"
        trustRootRef: rhtas-trust
  mode: enforce
