apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - admin-credentials-secret.yaml
  - pvc.yaml
  - agent-imagestream.yaml
  - agent-buildconfig.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: rhtas-demo
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
