apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}
