apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
stringData:
  mysql-root-password: "demo-root-password"
  mysql-replication-password: "demo-replication-password"
  mysql-password: "demo-password"
  mysql-user: "rhtas"
  mysql-database: "trillian"
